Refactor DAGs to better conform to Astronomer style opinions
astronomer/airflow-dbt-demo pull request #7
Opened 2022-03-31 17:18 UTC by denimalpaca

2022-03-31 18:52 UTC, josh-fell requested changes
Thanks for sprucing these up!

Small comment on some new developments/best practices being used in OSS example DAGs that we should carry over re: using `pendulum.datetime` for `start_date`.

2022-03-31 18:52 UTC, josh-fell commented on dags/dbt_advanced.py
>  from airflow.utils.dates import datetime
We shouldn't be importing from `datetime` from `airflow.utils.dates`. Ideally we should really be importing `pendulum.datetime` for `start_date`. Something on my backlog to transition our certified DAGs to at some point (see [this documentation](https://airflow.apache.org/docs/apache-airflow/stable/timezone.html#interpretation-of-naive-datetime-objects)). It's not a big deal (`datetime.datetime` vs. `pendulum.datetime`) unless folks want to use timezone-aware DAGs which _require_ `pendulum.datetime`. Just a good habit now.

2022-03-31 18:52 UTC, josh-fell commented on dags/dbt_advanced.py
>      description='A dbt wrapper for airflow',
```suggestion
    description='A dbt wrapper for Airflow.',
```

2022-04-04 14:12 UTC, denimalpaca commented on dags/dbt_advanced.py
>  from airflow.utils.dates import datetime
Noted and done.

2022-04-05 00:05 UTC, josh-fell requested changes

2022-04-05 00:05 UTC, josh-fell commented on requirements.txt
> +jsonschema==3.2.0
```suggestion
```
Not needed since `elt.py` is no longer a part of the repo.

2022-04-05 13:41 UTC, josh-fell approved these changes

2022-04-05 13:42 UTC, merged